score = 100

[judge]
judgeType = "classic"

[resourceLimits]
time = 1000
memory = 256

[task]
taskType = "subtask"

[[task.subtasks]]
score = 40

[[task.subtasks.cases]]
input = "1.in"
answer = "1.ans"

[[task.subtasks.cases]]
input = "2.in"
answer = "2.ans"

[[task.subtasks]]
score = 60

[[task.subtasks.cases]]
input = "3.in"
answer = "3.ans"

[[task.subtasks.cases]]
input = "4.in"
answer = "4.ans"